apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    name: nginx
    project: roboshop
    env: development

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      containerPort: 80