apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: multi-test
    project: prac-resources
    env: test

spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    cmd: ["sleep", "1000"]