apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
  labels:
    project: roboshop
  annotations:
    annot: annotationsusagepoddemo

spec:
  container:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]