apiVersion: v1
kind: Pod
metadata:
  name: envpod
  labels:
    project: roboshop
  annotations:
    usage: internal
  
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: k8's
    - name: trainer
      value: sivakumar