apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-demo
  labels:
    name: roboshop
  annotations:
    jenkins.url: https://jenkins.jd.com/build/5
  
spec:
  containers:
    name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    envFrom:
    - secretRef:
        name: pod-secret