apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    project: roboshop
    purpose: customer-demand
    duration: 120 hrs
    importance: high

spec:
  containers:
  - name: nginx
    image: nginx