apiVersion: v1
kind: Service
metadata:
  name: service-prac

spec:
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
---
apiVersion: v1
kind: Service
metadata:
  name: service-prac

spec:
  clusterIP: None
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic"
      resources:
        requests:
          storage: 1Gi