apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop

spec:
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high

  ports:
    - protocol: TCP
      port: 5672 #service port
      targetPort: 5672 #container port
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high
  ports:
    - protocol: TCP
      port: 5672 #service port
      targetPort: 5672 #container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      purpose: customer-demand
      importance: high # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        purpose: customer-demand
        importance: high # has to match .spec.selector.matchLabels
      namespace: roboshop 
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic"
      resources:
        requests:
          storage: 1Gi