apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  selector:
    purpose: blue-green
    project: roboshop
    colour: blue
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port