apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: cart
        image: prudhvimv/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart

        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
      component: cart
      project: roboshop
      tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  labels:
    component: cart
    project: roboshop
    tier: backend
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
