apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: taint
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: taint

  template:
    metadata:
      labels:
        purpose: taint
 
    spec:
      containers:
      - name: nginx
        image: nginx
