apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    purpose: affinity
    project: roboshop

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d
    spec:
      containers:
      - name: nginx
        image: nginx