apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    purpose: affinity
    project: roboshop

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/instance-type
            operator: In
            values:
            - t3.small   
            
  containers:
  - name: nginx
    image: nginx