apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
  labels:
    purpose: anti-affinity
    project: roboshop

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - us-east-1d  
            
  containers:
  - name: nginx
    image: nginx