apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    project: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    project: roboshop

spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
        topologyKey: topology.kubernetes.io/zone

  containers:
  - name: nginx
    image: nginx
