apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis

spec:
  selector:
      component: redis
      project: roboshop
      tier: db
  ports:
    - protocol: TCP
      port: 6379 #service port
      targetPort: 6379 #container port