apiVersion: v1
kind: Service
metadata:
  name: mongodb

spec:
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #container port
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless

spec:
  clusterIP: None
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      project: roboshop
      purpose: customer-demand
      importance: high # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        purpose: customer-demand
        importance: high # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: prudhvimv/mongodb:v1
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic"
      resources:
        requests:
          storage: 1Gi