apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop-dev
    region: us-east-1

managedNodeGroups:
- name: roboshop-dev-green
  instanceTypes: ["m5.large","t3.small", "t3.medium","c5.large"]
  desiredCapacity: 2 #  by default this value is 3
  spot: true

- name: roboshop-dev-blue
  instanceTypes: ["m5.large","t3.small", "t3.medium","c5.large"]
  desiredCapacity: 2 #  by default this value is 3
  spot: true