apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: frontend
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: prudhvimv/frontend:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: frontend

        ports:
        - name: liveness-port
          containerPort: 80

        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  type: LoadBalancer
  selector:
      component: frontend
      project: roboshop
      tier: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port