apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: prudhvimv/mongodb:v1
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb

spec:
  selector:
      component: mongodb
      project: roboshop
      tier: db
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #container port