apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop

spec:
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high

  ports:
    - protocol: TCP
      port: 6379 #service port
      targetPort: 6379 #container port
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    purpose: customer-demand
    importance: high
  ports:
    - protocol: TCP
      port: 6379 #service port
      targetPort: 6379 #container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      purpose: customer-demand
      importance: high # has to match .spec.template.metadata.labels
  serviceName: "redis-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        purpose: customer-demand
        importance: high # has to match .spec.selector.matchLabels
      namespace: roboshop 
    spec:
      containers:
      - name: redis
        image: redis:7
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic"
      resources:
        requests:
          storage: 1Gi