apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq

spec:
  selector:
      component: rabbitmq
      project: roboshop
      tier: db
  ports:
    - protocol: TCP
      port: 5672 #service port
      targetPort: 5672 #container port